language: python
sudo: required
dist: xenial

python:
   - "2.7"
   - "3.5"
   - "3.6"
   - "3.7"

branches:
    only:
        - master
        - develop

install:
    - pip install --upgrade pip setuptools wheel
    - pip install --upgrade pytest
    - pip install flake8
    - pip install six
    - pip install codecov
    - pip install pytest-cov
    - pip install pytest-pep8
    - pip install --only-binary=numpy numpy # Otherwise this would take ages
    - pip install -e .

script:
  # [TODO] add tests here

after_success:
    - codecov
