trigger:
- master
- test-azure

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    conda create -y -q -n testenv python=$(python.version)
  displayName: "Create Conda environment"

- script: |
    source /usr/share/miniconda/bin/activate testenv
    cd $(Build.SourcesDirectory)
    conda install -y conda-build anaconda-client
    conda build conda-recipe/meta.yaml -c michellab/label/dev -c rdkit -c conda-forge -c omnia -c bioconda --token $(anacondaToken) --user essexlab
    conda install -y -c michellab/label/dev -c rdkit -c conda-forge -c omnia -c bioconda -c essexlab protocaller
    python -m pip install --upgrade pip
    pip install pytest pytest-azurepipelines
    pip install -e .
  displayName: 'Install ProtoCaller'

- script: |
    source /usr/share/miniconda/bin/activate testenv
    python -m pytest test/
  displayName: 'Test ProtoCaller'