name: protocaller
channels:
  - essexlab
  - michellab
  - omnia
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - ambertools>=17.6
  - beautifulsoup4
  - biopython>=1.73
  - biosimspace>=2019.2.0
  - geckodriver
  - htmd-pdb2pqr
  - libcblas
  - mdanalysis
  - numpy
  - openbabel<=2.4.1
  - parmed>=3.1.0
  - pdbfixer>=1.5
  - pygtail
  - pymbar
  - pypdb
  - pytest
  - rdkit
  - requests
  - selenium
  - selenium-requests
  - tldextract
  - xmltodict