channels:
  - michellab/label/dev
  - accelera
  - rdkit
  - openbabel
  - AmberMD
  - salilab
  - conda-forge
  - omnia

dependencies:
  - python>=3.7
  - ambertools>=17.6
  - beautifulsoup4
  - biopython>=1.73
  - biosimspace
  - geckodriver
  - htmd-pdb2pqr>=2.1.1
  - mdanalysis
  - modeller
  - numpy==1.15.4
  - openbabel>=2.4.1
  - parmed>=3.1.0
  - pdbfixer>=1.5
  - pymbar
  - pytest
  - qt>=5.9.7
  - rdkit>=2018.03.4
  - requests
  - selenium
  - tldextract
  - xmltodict