package:
  name: protocaller
  version: 1.1.2

source:
  path: ../

build:
  noarch: python
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  script:
    - mkdir -p $PREFIX/site-packages
    - cp -r $RECIPE_DIR/../ProtoCaller $PREFIX/site-packages/ProtoCaller

requirements:
  build:
    - python>=3.7
    - numpy
  run:
    - python>=3.7
    - ambertools>=17.6
    - beautifulsoup4
    - biopython=1.76
    - biosimspace>=2019.2.0
    - geckodriver
    - htmd-pdb2pqr
    - libcblas
    - libnetcdf=4.6.2
    - mdanalysis
    - numpy
    - openbabel<=2.4.1
    - parmed>=3.1.0
    - pdbfixer>=1.5
    - propka=3.1.0
    - pygtail
    - pymbar
    - pytest
    - rdkit
    - requests
    - selenium
    - selenium-requests
    - sire=2019.2.0
    - tldextract
    - xmltodict

test:
  requires:
    - pytest

about:
  home: https://github.com/protocaller/protocaller
  summary: Full automation of high-throughput relative binding free energy simulations.
  license: GPL-3.0
  license_file: LICENSE