package:
  name: protocaller
  version: 1.1.0

source:
  path: ../

build:
  noarch: python
  script:
    - mkdir -p $PREFIX/site-packages
    - cp -r $RECIPE_DIR/../ProtoCaller $PREFIX/site-packages/ProtoCaller

requirements:
  build:
    - python>=3.7
    - numpy>=1.15.4
  run:
    - python>=3.7
    - ambertools>=17.6
    - beautifulsoup4
    - biopython>=1.73
    - biosimspace>=2019.2.0
    - geckodriver
    - htmd-pdb2pqr
    - libcblas
    - mdanalysis
    - numpy==1.15.4
    - openbabel
    - parmed>=3.1.0
    - pdbfixer>=1.5
    - pygtail
    - pymbar
    - pypdb
    - pytest
    - rdkit
    - requests
    - selenium
    - selenium-requests
    - tldextract
    - xmltodict

test:
  requires:
    - pytest

about:
  home: https://github.com/miroslav351/protocaller
  summary: Full automation of high-throughput relative binding free energy simulations.
  license: GPL-3.0
  license_file: LICENSE