package:
  name: protocaller-dev
  version: 0.1.0

source:
  git_url: https://github.com/miroslav351/ProtoCaller.git

build:
  noarch: python
  script:
    - mkdir -p $PREFIX/site-packages
    - cp -r $RECIPE_DIR/../ProtoCaller $PREFIX/site-packages/ProtoCaller

requirements:
  build:
    - python >=3.7
    - numpy >=1.15.4
  run:
    - python>=3.7
    - ambertools>=17.6
    - beautifulsoup4
    - biopython>=1.73
    - geckodriver
    - mdanalysis
    - modeller
    - numpy==1.15.4
    - openbabel>=2.4.1
    - parmed>=3.1.0
    - pymbar
    - pytest
    - rdkit>=2018.03.4
    - requests
    - selenium
    - tldextract
    - xmltodict

test:
  requires:
    - pytest